apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  ports:
  - name: "8180"
    port: 8180
    targetPort: 80
  selector:
    service: udagram-frontend
