language: node_js
node_js:
  - 11

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker build -t udagram-frontend ./project/udagram-frontend
  - docker build -t udagram-reverseproxy ./project/udagram-reverseproxy
  - docker tag udagram-api-feed rochanajayakumar/udagram-api-feed:v1
  - docker tag udagram-api-user rochanajayakumar/udagram-api-user:v1
  - docker tag udagram-frontend rochanajayakumar/udagram-frontend:v1
  - docker tag udagram-reverseproxy rochanajayakumar/udagram-reverseproxy:v1 

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push rochanajayakumar/udagram-api-feed:v1
  - docker push rochanajayakumar/udagram-api-user:v1
  - docker push rochanajayakumar/udagram-frontend:v1
  - docker push rochanajayakumar/udagram-reverseproxy:v1

